=== UO295662/SEW2/F1Desktop/xml/circuito.dtd
<!ELEMENT circuito (nombre, longitud_pista, anchura, fecha, hora, vueltas, localidad, pais, bibliografia, galeria_fotos, galeria_videos?, coordenadas_centro, tramos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT longitud_pista (#PCDATA)>
<!ELEMENT anchura (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT vueltas (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>

<!ELEMENT bibliografia (referencia+)>
<!ELEMENT referencia (#PCDATA)>

<!ELEMENT galeria_fotos (foto+)>
<!ELEMENT foto (#PCDATA)>
<!ATTLIST foto archivo CDATA #REQUIRED>

<!ELEMENT galeria_videos (video*)>
<!ELEMENT video (#PCDATA)>
<!ATTLIST video archivo CDATA #REQUIRED>

<!ELEMENT coordenadas_centro (latitud, longitud, altitud)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT altitud (#PCDATA)>

<!ELEMENT tramos (tramo+)>
<!ELEMENT tramo (distancia, coordenadas, sector)>
<!ELEMENT distancia (valor, unidad)>
<!ELEMENT valor (#PCDATA)>
<!ELEMENT unidad (#PCDATA)>
<!ELEMENT coordenadas (latitud, longitud, altitud)>
<!ELEMENT sector (#PCDATA)>

=== UO295662/SEW2/F1Desktop/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">
<circuito>
    <nombre>Enzo E Dino Ferrari</nombre>
    <longitud_pista>4909.0</longitud_pista>
    <anchura>12</anchura>
    <fecha>2024-05-19</fecha>
    <hora>15:00:00</hora>
    <vueltas>63</vueltas>
    <localidad>Imola</localidad>
    <pais>Italia</pais>

    <bibliografia>
        <referencia>https://es.wikipedia.org/wiki/Autodromo_Enzo_e_Dino_Ferrari</referencia>
        <referencia>https://www.imolaf1.com/es</referencia>
        <referencia>https://www.formula1.com/en/racing/2024/emiliaromagna/circuit</referencia>
    </bibliografia>

    <galeria_fotos>
        <foto archivo="multimedia/Panorama.jpg">Panorama del circuito</foto>
        <foto archivo="multimedia/RectaMeta.jpg">Recta principal y zona de meta</foto>
        <foto archivo="multimedia/Curva.jpg">Curva Parab√≥lica</foto>
    </galeria_fotos>

    <galeria_videos>
        <video archivo="multimedia/UnavueltaalCircuitodeImolaconMaxVerstappen.mp4">Vuelta completa al circuito</video>
    </galeria_videos>

    <coordenadas_centro>
        <latitud>44.342189</latitud>
        <longitud>11.712222</longitud>
        <altitud>162</altitud>
    </coordenadas_centro>

    <tramos>
        <tramo>
            <distancia>
                <valor>56.51</valor>
                <unidad>m</unidad>
            </distancia>
            <coordenadas>
                <latitud>44.3441</latitud>
                <longitud>11.7139</longitud>
                <altitud>35</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia>
                <valor>222.64</valor>
                <unidad>m</unidad>
            </distancia>
            <coordenadas>
                <latitud>44.3444</latitud>
                <longitud>11.7122</longitud>
                <altitud>37</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia>
                <valor>80.52</valor>
                <unidad>m</unidad>
            </distancia>
            <coordenadas>
                 <latitud>44.3442</latitud>
                 <longitud>11.7094</longitud>
                <altitud>37</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia>
                <valor>207.07</valor>
                <unidad>m</unidad>
            </distancia>
            <coordenadas>
               <latitud>44.3439</latitud>
                <longitud>11.7081</longitud>
                <altitud>37</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia>
                <valor>127.04</valor>
                <unidad>m</unidad>
            </distancia>
            <coordenadas>
               <latitud>44.3433</latitud>
                <longitud>11.7078</longitud>
                <altitud>37</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia>
                <valor>61.97</valor>
                <unidad>m</unidad>
            </distancia>
            <coordenadas>
                 <latitud>44.3428</latitud>
                <longitud>11.7064</longitud>
                <altitud>37</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia>
                <valor>136.24</valor>
                <unidad>m</unidad>
            </distancia>
            <coordenadas>
                 <latitud>44.3391</latitud>
                <longitud>11.7042</longitud>
                <altitud>38</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia>
                <valor>435.68</valor>
                <unidad>m</unidad>
            </distancia>
            <coordenadas>
                <latitud>44.3383</latitud>
                <longitud>11.7044</longitud>
                <altitud>39</altitud>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia>
                <valor>123.98</valor>
                <unidad>m</unidad>
            </distancia>
            <coordenadas>              
                <latitud>44.3369</latitud>
                <longitud>11.7019</longitud>
                <altitud>40</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia>
                <valor>142.09</valor>
                <unidad>m</unidad>
            </distancia>
            <coordenadas>
                <latitud>44.3366</latitud>
                <longitud>11.7019</longitud>
                <altitud>45</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia>
                <valor>34,01</valor>
                <unidad>m</unidad>
            </distancia>
            <coordenadas>
                 <latitud>44.3364</latitud>
                <longitud>11.7022</longitud>
                <altitud>47</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia>
                <valor>195.35</valor>
                <unidad>m</unidad>
            </distancia>
            <coordenadas>    
                <latitud>44.3366</latitud>
                <longitud>11.7067</longitud>
                <altitud>64</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia>
                <valor>290.21</valor>
                <unidad>m</unidad>
            </distancia>
            <coordenadas>
                 <latitud>44.3364</latitud>
                    <longitud>11.7092</longitud>
                <altitud>67</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia>
                <valor>27,77</valor>
                <unidad>m</unidad>
            </distancia>
            <coordenadas>
                 <latitud>44.3366</latitud>
                 <longitud>11.7097</longitud>
                <altitud>67</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia>
                <valor>80,85</valor>
                <unidad>m</unidad>
            </distancia>
            <coordenadas>
                <latitud>44.3372</latitud>
                <longitud>11.7103</longitud>
                <altitud>65</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia>
                <valor>88,6</valor>
                <unidad>m</unidad>
            </distancia>
            <coordenadas>
                <latitud>44.3380</latitud>
                <longitud>11.7106</longitud>
                <altitud>61</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia>
                <valor>221,77</valor>
                <unidad>m</unidad>
            </distancia>
            <coordenadas>
                 <latitud>44.3400</latitud>
                <longitud>11.7100</longitud>
                <altitud>46</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia>
                <valor>111,2</valor>
                <unidad>m</unidad>
            </distancia>
            <coordenadas>
                <latitud>44.3408</latitud>
                <longitud>11.7106</longitud>
                <altitud>46</altitud>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia>
                <valor>438,93</valor>
                <unidad>m</unidad>
            </distancia>
            <coordenadas>
                <latitud>44.3405</latitud>
                <longitud>11.7114</longitud>
                <altitud>65</altitud>
            </coordenadas>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia>
                <valor>34,79</valor>
                <unidad>m</unidad>
            </distancia>
            <coordenadas>
                <latitud>44.3402</latitud>
                <longitud>11.7173</longitud>
                <altitud>65</altitud>
            </coordenadas>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia>
                <valor>213,65</valor>
                <unidad>m</unidad>
            </distancia>
            <coordenadas>
                <latitud>44.3411</latitud>
                <longitud>11.7198</longitud>
                <altitud>64</altitud>
            </coordenadas>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia>
                <valor>103,68</valor>
                <unidad>m</unidad>
            </distancia>
            <coordenadas>
                <latitud>44.3417</latitud>
                <longitud>11.7208</longitud>
                <altitud>53</altitud>
            </coordenadas>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia>
                <valor>248,86</valor>
                <unidad>m</unidad>
            </distancia>
            <coordenadas>
                 <latitud>44.3430</latitud>
                <longitud>11.7228</longitud>
                <altitud>49</altitud>
            </coordenadas>
            <sector>3</sector>
        </tramo>
        <tramo>
